services:
  mongo:
    image: mongo:7
    container_name: wardenai-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - wardenai_mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: wardenai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  wardenai_mongo_data: